language: rust


before_install:
  - uname -a
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-add-repository --yes ppa:gqrx/releases
  - sudo apt-get update -qq
  - sudo apt-get -qq install libusb-dev libpulse-dev libsdl2-dev librtlsdr-dev

script:
  - cargo update
  - cargo build --verbose
