[package]
name = "kissfft"
version = "0.0.2"
authors = ["Ian Daniher <itdaniher@gmail.com>"]

build = ["make -C libkissfft", "mv ./libkissfft/libkissfft.so /usr/local/lib/"]

[dependencies.num]
git = "https://github.com/rust-lang/num"

[lib]
name = "kissfft"
