[package]
name = "kissfft"
version = "0.0.2"
authors = ["Ian Daniher <itdaniher@gmail.com>"]
build = "make -C libkissfft"

[dependencies.num]
git = "https://github.com/rust-lang/num"

[lib]
name = "kissfft"
