[package]

name = "vidsink"
version = "0.0.2"
authors = ["Ian Daniher <itdaniher@gmail.com>"]

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2.git"

[dependencies.dsputils]
path = "../dsputils/"

[lib]
name = "vidsink2"
