[package]
name = "bitfount"
version = "0.0.2"
authors = ["Ian Daniher <itdaniher@gmail.com>"]

[dependencies.num]
git = "https://github.com/rust-lang/num"

[dependencies.rtlsdr]
path = "../rtlsdr"

[dependencies.dsputils]
path = "../dsputils"

[lib]
name = "bitfount"
